pod-server: replace IMAGE_INSTALL_append with IMAGE_INSTALL +=
"IMAGE_INSTALL +=" will override the definition of
"IMAGE_INSTALL ?=" defined in the following inherited
core-image, and this is what we expected.

It will cause the unbuildable recipes "shadowpackagegroup_core_boot" error.

The nucleo-t project configure error information is as following:
============================================================================
ERROR: Nothing RPROVIDES 'shadowpackagegroup-core-boot' (but
layers/wr-nucleo-t/nucleo-t/base/recipes-base/images/wrlinux-image-nucleo-t.bb
RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'shadowpackagegroup-core-boot' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['shadowpackagegroup-core-boot']

Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>