consul-migrate: Fix up the consul-migrate build issue for the arm arch
Issue: OVP-2572

Inherit the golang class's common settings and remove those
redundancy sectons and class's common settings has enabled cgo, thus
it will fix the following error:

ERROR: Function failed: do_compile (log file is located at
bitbake_build/tmp/work/cortexa7t2hf-
vfp-neon-wrs-linux-gnueabi/consul-migrate/git-r0/temp/do_compile/log.do_compile.68285)
ERROR: Logfile of failure stored in:
bitbake_build/tmp/work/cortexa7t2hf-vfp-neon-wrs-linux-gnu
eabi/consul-migrate/git-r0/temp/do_compile/log.do_compile.68285
Log data follows:
| DEBUG: Executing shell function do_compile
|
../../../../../sysroots/fsl-ls10xx/usr/local/go/src/github.com/hashicorp/raft-mdb/mdb_store.go:5:2:
C source files not allowed when not using cgo: mdb.c midl.c
| WARNING:
temp/do_compile/run.do_compile.68285:1 exit 1 from
|   go install github.com/hashicorp/consul-migrate
| ERROR: Function failed: do_compile (log file is located at
bitbake_build/tmp/work/cortexa7t2h
f-vfp-neon-wrs-linux-gnueabi/consul-migrate/git-r0/temp/do_compile/log.do_compile.68285)
NOTE: recipe consul-migrate-git-r0: task do_compile: Failed

Signed-off-by: fupan li <fupan.li@windriver.com>