overc-system-agent: Fix QA errors for python
The overc-system-agent should be using python3 so as to fix this
problem reported by bitbake:

ERROR: overc-system-agent-1.2-r0 do_package_qa: QA Issue:
/opt/overc-system-agent/factory_clean.py contained in package
overc-system-agent requires /usr/bin/python, but no providers found in
RDEPENDS_overc-system-agent? [file-rdeps]

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>