overc: decouple mutilib/x86 from the distro level to the arch level
At the moment, you can't use the reference copies of overc local.conf
for !x86 (like say MACHINE qemuarm64) because you will get this error:

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Toolchain tunings invalid:
Tuning 'x86' has no defined features, and cannot be used.

Make the multilib setting specific to x86_64 target arch, so that we
can build other arch that don't need it or support it.  This also paves
the way for further arch specific configuration in the future.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>