upower: package systemd files
The uprev of upower in meta-oe forgot to package systemd files, which results
in the following error:

  ERROR: upower-0.99.4-r0 do_package: QA Issue: upower: Files/directories were installed but not shipped in any package:
    /lib/systemd
    /lib/systemd/system
    /lib/systemd/system/upower.service
  Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.

So we inherit systemd and package them, and all is well :)

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>