vim: add temporary local SRC_URI
Unclear how this works upstream but I'm sure it will be sorted out
in short order, so this is just a temporary workaround to avoid:

ERROR: No checksum specified for /home/paul/poky/build/downloads/vim_vim.googlecode.com_.hg._v7-4-481.tar.gz, please add at least one to the recipe:
SRC_URI[md5sum] = "c2ca0c0fb1a2d75036f831fef56b4792"
SRC_URI[sha256sum] = "d52a52a6297921699d2476e230604f15f5d24d886929a1dcc845390e67bad3af"
ERROR: Function failed: Fetcher failure for URL: 'http://downloads.yoctoproject.org/mirror/sources/vim_vim.googlecode.com_.hg._v7-4-481.tar.gz;protocol=https;module=vim'. Missing SRC_URI checksum
ERROR: Logfile of failure stored in: /home/paul/poky/build/tmp/work/core2-64-poky-linux/vim/7.4.481-r0/temp/log.do_fetch.11544
ERROR: Task 2421 (/home/paul/poky/meta-openembedded/meta-oe/recipes-support/vim/vim_7.4.481.bb, do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 2764 tasks of which 2762 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>