packagegroup-xfce.bb: replace xfce4-mixer to xfce4-pulseaudio-plugin
As xfce4-mixer is replaced with xfce4-pulseaudio-plugin
in commit[409fb4baa xfce4-mixer: Remove recipe]
under meta-xfce, so update it also in packagegroup-xfce
for overc to fix below error:
ERROR: Nothing RPROVIDES 'lib32-xfce4-mixer' (but virtual:multilib:lib32:/build/layers/meta-overc/meta-cube/recipes-core/packagegroups/packagegroup-xfce.bb RDEPENDS on or otherwise requires it)
ERROR: Required build target 'cube-desktop' has no buildable providers.
Missing or unbuildable dependency chain was: ['cube-desktop', 'lib32-cube-desktop', 'lib32-packagegroup-xfce', 'lib32-xfce4-mixer']

Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>