packagegroup-builder: drop eglibc-gconv-ibm850
To fix:

  ERROR: Nothing RPROVIDES 'eglibc-gconv-ibm850'
  (but /meta-builder/recipes-core/packagegroups/packagegroup-builder.bb RDEPENDS
  on or otherwise requires it)

Checking OE history, it was added to the self-host stuff in order
to provide mcopy, but who uses that now that floppies are dead?

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>