postinsts: drop custom systemd enable postinsts
When these postinsts were created there were bugs in the systemd
bbclass that prevented services from being properly enabled. So
we took the invokation of sysctrl into our recipes.

That is resolved now, and the postinsts throw errors:

NOTE: Executing RunQueue Tasks
ERROR: cube-dom0-0.6-r0 do_rootfs: Postinstall scriptlets of ['etcd', 'dom0-init'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.  Details of the failure are in

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>