cube-update: Remove #!/bin/false from config.default
The config.default is never going to be run directly by an end user.
It also causes a problem for building with usrmerge:

ERROR: cube-dom0-0.6-r0 do_rootfs: Could not invoke dnf.
Error:
 Problem: conflicting requests
  - nothing provides /bin/false needed by cube-update-1.0-r0.core2_64

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>