wiggle: add build depends on ncurses
To fix:

| vpatch.c:40:20: fatal error: curses.h: No such file or directory
|  #include <curses.h>
|                     ^
| compilation terminated.
| make: *** [vpatch.o] Error 1
| make: *** Waiting for unfinished jobs....
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at tmp/work/corei7-64-poky-linux/wiggle/1.0-r1/temp/log.do_compile.45305)
ERROR: Task 3288 (meta-builder/recipes-devtools/wiggle/wiggle_1.0.bb, do_compile) failed with exit code '1'

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>