initramfs: ensure we don't run a default configure step
When we manually bitbake the initramfs, we now see this error:

NOTE: Executing RunQueue Tasks
ERROR: initramfs-cube-builder-1.0-r9 do_configure: Function failed: do_configure (log file is located at /home/paul/poky/build/tmp/work/core2-64-overc-linux/initramfs-cube-builder/1.0-r
9/temp/log.do_configure.17631)
ERROR: Logfile of failure stored in: /home/paul/poky/build/tmp/work/core2-64-overc-linux/initramfs-cube-builder/1.0-r9/temp/log.do_configure.17631
Log data follows:
| DEBUG: Executing shell function do_configure
| find: ‘/home/paul/poky/build/tmp/work/core2-64-overc-linux/initramfs-cube-builder/1.0-r9/license-destdir’: No such file or directory
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/paul/poky/build/tmp/work/core2-64-overc-linux/initramfs-cube-builder/1.0-r9/temp/log.do_configure.17631)
ERROR: Task (/home/paul/poky/meta-overc/meta-cube/recipes-core/initrdscripts/initramfs-cube-builder.bb:do_configure) failed with exit code '1'

As the initramfs is just an assembly of bits, it doesn't need any
configure step wandering in and snooping around for this and that.
Hence we just dummy out the configure step.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>