samba: remove unnecessary DEPENDS on ctdb
During rootfs creation the following error is being hit

  Preparing...         ######################################## [  0%]
  warning: Removing ctdb-2.5.1-r0@core2_64 due to file /usr/bin/ctdb
  conflicting with samba-4.4.2-r0@core2_64
  error: ctdb-dev-2.5.1-r0 conflicts with ctdb = 2.5.1-r0

Looking at the relationship between samba and ctdb it appears that the
landscape has changed some starting in version 4.2. Samba now includes
and installs ctdb instead of relying on stand-alone ctdb. Referencing
https://wiki.samba.org/index.php/CTDB_Setup we see this activated by
'--with-cluster-support' which we do pass to configure based on the
bb.

Dropping the DEPENDS on ctdb resolves this issue.

A similar change has been sent to meta-openembedded, after it is
merged we can drop this change.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>