package-name: python3 no longer supports iteritems
...and so you get this failure:

Exception: AttributeError: 'OrderedDict' object has no attribute 'iteritems'

...from package_name_hook.  The new name is now just "items"

Similar changes in git://git.pokylinux.org/poky 3af9f6b88fcc5d.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>