git: do not try and auto depend on bash completions.
Upstream changes combine with this to cause the build of native
git to depend on native bash completion, which then fails with:

ERROR: Nothing PROVIDES 'nativesdk-bash-completion' (but virtual:nativesdk:/home/paul/poky/meta/recipes-devtools/git/git_2.3.0.bb DEPENDS on or otherwise requires it).

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>