linux-yocto: fixup compile failure on 4.19
Fixes
| kernel/exit.c:95:11: error: 'struct task_struct' has no member named 'pids'; did you mean 'pid'?
|   if (tsk->pids[PIDTYPE_PID].pid &&
|            ^~~~
|            pid

Introduced by mainline commit 2c4704756cab [pids: Move the pgrp and
session pid pointers from task_struct to signal_struct]. Which moved
the pids to the signal structure to save some space.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>